### ISSUE TITLE
Register MLJRegistry.jl in the General registry?

### ISSUE THREAD

**Issue by DilumAluthge** [alan-turing-institute/MLJRegistry.jl#2]
MLJ.jl, MLJBase.jl and MLJModels.jl are all registered in the [General registry](https://github.com/JuliaRegistries/General). However, MLJRegistry.jl is not currently registered.

Could we register MLJRegistry.jl in the General registry?

**Comment by ablaom** [comment]
Thanks for that.

MLJRegistry is really just for "administrators". In particular, it is not a code dependency of any of the other packages.  MLJ uses the file "Metadata.toml" located there, but access is "direct" (using a neat package called RemoteFiles.jl).

Is there some specific reason you would like to have it registered?

**Comment by DilumAluthge** [comment]
Ahhh, I see. I knew that MLJ used the "Metadata.toml" file, but I didn't realize that you used RemoteFiles.jl to download it.

What are the advantages and disadvantages of using RemoteFiles.jl versus making MLJRegistry a code dependency of MLJ?

**Comment by ablaom** [comment]
Making MLJRegistry a dependency leads to Dependency Hell because MLJRegistry depends on MLJ. Ie, to avoid circular dependencies.

**Comment by DilumAluthge** [comment]
Ahh that's a pretty big advantage.
